// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Simple.proto

package io.grpc;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 value = 2;</code>
   */
  int getValue();
}
