// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Simple.proto

package io.grpc;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>optional int64 result = 2;</code>
   */
  long getResult();
}
